site_name: Black-Scholes Option Pricing Model
site_url: https://rmaluski.github.io/black-scholes-option-pricing-model/
theme:
  name: material
docs_dir: docs
nav:
  - Home: index.md
  - Usage: usage.md
  - API Reference: api.md
